[platformio]
default_envs = m5stack-core-esp32

[env:m5stack-core-esp32]
platform = espressif32@6.10.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
build_flags =
  -Wall
  -Wextra
  -Wno-unused-parameter
lib_deps =
  m5stack/M5Stack@0.4.6
  adafruit/Adafruit SHT31 Library@2.2.2
  bblanchon/ArduinoJson@7.4.3
  https://github.com/jmstriegel/Plantower_PMS7003.git#4b4c83b300b18f0f9c2c1494b1f910c4cb8cbe67
